name: iris-ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gcs]
          pip install pytest

      - name: Pull data and models
        run: dvc pull --force

      - name: Run tests
        run: pytest
